defaults:
  - _self_
  - default

dataset_name: EB-NeRD
dataset_dir: ${path.data_dir}/ebnerd_large
dataset_lang: danish

train_len: 12063890 #2232748
val_len: 12566385 #376471
test_len: 13536710 #2370727

pos_count: 3383656

# Info
word_num: 101232
user_num: 788090 #711223
category_num: 32 #18
subcategory_num: 285
